server:
    port: 8090
    servlet:
        context-path: /
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    connection-timeout: 60000
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: example
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        logSlowSql: true
    druid:
        stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: root
        login-password: root
        allow:
        deny:
    filter:
        stat:
            log-slow-sql: true
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true
    redis:
        host: 127.0.0.1
        port: 6379
        password: password
mybatis-plus:
#    将下划线映射到驼峰大小写
    configuration:
        map-underscore-to-camel-case: true